export const getMonacoLanguage = (languageId) => {
  switch (languageId) {
    case 45:
      return "asm";
    case 46:
      return "bash";
    case 47:
      return "basic";
    case 104:
    case 110:
    case 75:
    case 103:
    case 48:
    case 49:
    case 50:
      return "c";
    case 76:
    case 105:
    case 52:
    case 53:
    case 54:
      return "cpp";
    case 86:
      return "clojure";
    case 51:
      return "csharp";
    case 77:
      return "cobol";
    case 55:
      return "commonlisp";
    case 90:
      return "dart";
    case 56:
      return "d";
    case 57:
      return "elixir";
    case 58:
      return "erlang";
    case 44:
      return "executable";
    case 87:
      return "fsharp";
    case 59:
      return "fortran";
    case 60:
    case 95:
    case 106:
    case 107:
      return "go";
    case 88:
      return "groovy";
    case 61:
      return "haskell";
    case 96:
    case 91:
    case 62:
      return "java";
    case 63:
    case 93:
    case 97:
    case 102:
      return "javascript";
    case 78:
    case 111:
      return "kotlin";
    case 64:
      return "lua";
    case 89:
      return "multi-file";
    case 79:
      return "objectivec";
    case 65:
      return "ocaml";
    case 66:
      return "octave";
    case 67:
      return "pascal";
    case 85:
      return "perl";
    case 68:
    case 98:
      return "php";
    case 43:
      return "plaintext";
    case 69:
      return "prolog";
    case 70:
    case 92:
    case 100:
    case 109:
    case 71:
      return "python";
    case 80:
    case 99:
      return "r";
    case 72:
      return "ruby";
    case 73:
    case 108:
      return "rust";
    case 81:
    case 112:
      return "scala";
    case 82:
      return "sql";
    case 83:
      return "swift";
    case 74:
    case 94:
    case 101:
      return "typescript";
    case 84:
      return "vb";
    default:
      return "plaintext";
  }
};

export const getDefaultFileNameForMonaco = (monacoLang) => {
  switch (monacoLang) {
    case "javascript":
      return "main.js";
    case "typescript":
      return "main.ts";
    case "python":
      return "main.py";
    case "java":
      return "Main.java";
    case "c":
      return "main.c";
    case "cpp":
      return "main.cpp";
    case "csharp":
      return "Program.cs";
    case "go":
      return "main.go";
    case "rust":
      return "main.rs";
    case "php":
      return "index.php";
    case "ruby":
      return "main.rb";
    case "swift":
      return "main.swift";
    case "kotlin":
      return "Main.kt";
    case "scala":
      return "Main.scala";
    case "sql":
      return "query.sql";
    case "bash":
      return "script.sh";
    case "plaintext":
      return "untitled.txt";
    case "asm":
      return "main.asm";
    case "basic":
      return "main.bas";
    case "clojure":
      return "main.clj";
    case "cobol":
      return "main.cbl";
    case "commonlisp":
      return "main.lisp";
    case "dart":
      return "main.dart";
    case "d":
      return "main.d";
    case "elixir":
      return "main.ex";
    case "erlang":
      return "main.erl";
    case "executable":
      return "program.sh";
    case "fsharp":
      return "Program.fs";
    case "fortran":
      return "main.f90";
    case "groovy":
      return "Main.groovy";
    case "haskell":
      return "Main.hs";
    case "lua":
      return "main.lua";
    case "objectivec":
      return "main.m";
    case "ocaml":
      return "main.ml";
    case "octave":
      return "main.m";
    case "pascal":
      return "main.pas";
    case "perl":
      return "main.pl";
    case "prolog":
      return "main.pl";
    case "multi-file":
      return "project.txt";
    case "r":
      return "main.R";
    case "vb":
      return "Program.vb";
    default:
      return `main.${monacoLang}`;
  }
};

export const getDefaultFileNameForLanguage = (languageId) => {
  const monacoLang = getMonacoLanguage(languageId);
  return getDefaultFileNameForMonaco(monacoLang);
};
